import { LogOut, ShieldCheck } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { navigation, userNav } from '../data/mockData';
import { useAuth } from '../context/AuthContext';
import { Button } from './ui';
import { cn } from '../utils/cn';

export interface SidebarProps { readonly open: boolean; readonly onNavigate: () => void; }
export function Sidebar({ open, onNavigate }: SidebarProps) { const location = useLocation(); const { user, profile, signOut } = useAuth(); const displayName = profile?.full_name ?? user?.name ?? user?.email ?? 'Security analyst'; const initials = displayName.trim().split(/\s+/).slice(0, 2).map((part) => part.charAt(0).toUpperCase()).join('') || 'AS'; const subtitle = profile?.role ?? user?.email ?? 'Security analyst'; const group = (items: typeof navigation) => items.map(({ label, to, icon: Icon }) => <Link key={to} to={to} onClick={onNavigate} className={cn('group flex items-center gap-3 rounded px-3 py-2.5 text-sm transition', location.pathname === to ? 'bg-primary/10 text-primary shadow-[inset_2px_0_0_0_currentColor]' : 'text-on-surface-variant hover:bg-surface-high hover:text-on-surface')}><Icon size={18} /><span>{label}</span></Link>); return <aside className={cn('fixed inset-y-0 left-0 z-40 flex w-[280px] flex-col border-r bg-surface-lowest transition-transform lg:static lg:translate-x-0', open ? 'translate-x-0' : '-translate-x-full')}><Link to="/dashboard" className="flex items-center gap-3 border-b px-6 py-5" onClick={onNavigate}><span className="grid h-8 w-8 place-items-center rounded bg-primary text-primary-foreground"><ShieldCheck size={19} /></span><span className="font-display text-lg font-bold tracking-tight">CyberShield <em className="not-italic text-primary">AI</em></span></Link><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-5">{group(navigation)}<p className="eyebrow px-3 pb-2 pt-6">Workspace</p>{group(userNav as typeof navigation)}</nav><div className="border-t p-4"><div className="flex items-center gap-3 rounded bg-surface-container p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-secondary/15 font-mono text-sm text-secondary">{initials}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{displayName}</p><p className="truncate text-xs text-on-surface-variant">{subtitle}</p></div></div><Button variant="ghost" className="mt-3 w-full" onClick={() => { void signOut(); }}><LogOut size={16} /> Sign out</Button></div></aside>; }
