import { KeyRound, Save, ShieldAlert, UserRound } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { Badge, Button, Card, TextInput } from '../components/ui';

export interface ProfilePageProps { readonly editable?: boolean; }
export function ProfilePage({ editable = true }: ProfilePageProps) { return <><PageHeader eyebrow="Account" title="User Profile" description="Manage the workspace identity shown across CyberShield AI." /><div className="grid max-w-4xl gap-5 md:grid-cols-[0.8fr_1.2fr]"><Card className="flex flex-col items-center p-6 text-center"><span className="grid h-20 w-20 place-items-center rounded-full bg-secondary/15 text-secondary"><UserRound size={35} /></span><h2 className="mt-4 font-display text-xl font-semibold">Avery Sharma</h2><p className="mt-1 text-sm text-on-surface-variant">Security Analyst</p><Badge tone="success">Active workspace</Badge></Card><Card className="p-6"><h2 className="font-display text-lg font-semibold">Personal information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><TextInput label="Full name" defaultValue="Avery Sharma" /><TextInput label="Role" defaultValue="Security Analyst" /><div className="sm:col-span-2"><TextInput label="Email address" defaultValue="avery@cybershield.dev" /></div></div>{editable && <Button className="mt-6"><Save size={16} /> Save changes</Button>}</Card></div></>; }

export interface SettingsPageProps { readonly notifications?: boolean; }
export function SettingsPage({ notifications = true }: SettingsPageProps) { return <><PageHeader eyebrow="Workspace" title="Settings" description="Configure display preferences and demo security notifications." /><div className="max-w-3xl space-y-5"><Card className="p-6"><h2 className="font-display text-lg font-semibold">Notification preferences</h2>{['Critical threat alerts', 'Weekly security digest', 'Scan completion updates'].map((label, index) => <label className="mt-5 flex items-center justify-between" key={label}><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-on-surface-variant">Static preference control</span></span><input className="h-5 w-5 accent-primary" defaultChecked={notifications && index !== 2} type="checkbox" /></label>)}</Card><Card className="p-6"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 text-warning" /><div><h2 className="font-display text-lg font-semibold">Demo environment</h2><p className="mt-2 text-sm leading-6 text-on-surface-variant">This Phase 1 frontend intentionally uses no API connection, authentication, or saved preferences.</p></div></div></Card></div></>; }

export interface NotFoundPageProps { readonly message?: string; }
export function NotFoundPage({ message = 'The security console page you requested could not be located.' }: NotFoundPageProps) { return <div className="flex min-h-[70vh] items-center justify-center"><div className="max-w-lg text-center"><p className="font-mono text-8xl font-bold text-primary/30">404</p><h1 className="mt-4 font-display text-3xl font-bold">Signal lost</h1><p className="mt-3 text-on-surface-variant">{message}</p><Button className="mt-7" onClick={() => window.history.back()}><KeyRound size={16} /> Return to safety</Button></div></div>; }
